name = "Stitches Pack"
author = "Stitches"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffea2d0bc1e36e048c4d7601cbfef6634069b0faa1879636e845d9390f222789"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
